### ISSUE TITLE
Array bounds violated

### ISSUE THREAD

**Issue by Dirk-** [soffes/SAMCubicSpline#1]
Hi,

first, thanks for the code!

I think I found a problem in `initWithPoints`:
When calculating `h[i]` and `k[i]`, you use `x[i + 1]` and `a[i + 1]`. Since `i` goes up to `n-1`, you access storage outside the array bounds. Should `n` be `count-1`, like you suggest in your comment?

Dirk

**Comment by soffes** [comment]
I never ran into this when I used it but that sounds right. Can you send me a pull request?

**Comment by Dirk-** [comment]
I just created one.

Am 26.03.2018 um 17:31 schrieb Sam Soffes <notifications@github.com<mailto:notifications@github.com>>:


I never ran into this when I used it but that sounds right. Can you send me a pull request?

**Comment by soffes** [comment]
Merged!
